public Class A0
{
public Account CreateRecord(String name)  //method to create Account
{
//Add comment for Account A1 Testasdasdasdasdasd
Account a121 = new Account();asdasdas
a121.Name = name;dasdasd
return a121;asdasd
//this is the test comment
}
public Account CreateRecord(String name)  //methasdasdod to create Account
{
//Add comment for Account A1 Test
Account a121 = new Account();asdasd
a121.Name = name;
return a121;
//this is the test commentasdasd
}
}
